version: 0.2

phases:
  pre_build:
    commands:
      - |
        echo "Pre Build: authenticate to target ECR"
  build:
    commands:
      - |
        echo "Build: Hello, CodeBuild!"
  post_build:
    commands:
      - echo "Post:post_build phase"
