version: 0.2

env:
  variables:
    SOURCE_AWS_ACCOUNT_ID: "082830052325"
    SOURCE_AWS_REGION: "us-east-1"
  secrets-manager:
    SOURCE_AWS_ACCESS_KEY_ID: agaba-cn-ecr-user:access-key
    SOURCE_AWS_SECRET_ACCESS_KEY: agaba-cn-ecr-user:secret
    SOURCE_AWS_SESSION_TOKEN: agaba-cn-ecr-user:session-token
phases:
  pre_build:
    commands:
      - echo Setting up source profile
      - aws configure --profile source-ecr set region $SOURCE_AWS_REGION
      - aws configure --profile source-ecr set output "json"
      - aws configure --profile source-ecr set aws_secret_access_key "$SOURCE_AWS_SECRET_ACCESS_KEY"
      - aws configure --profile source-ecr set aws_access_key_id "$SOURCE_AWS_ACCESS_KEY_ID"
      - aws configure --profile source-ecr set aws_session_token "$SOURCE_AWS_SESSION_TOKEN"
      - echo Logging in to Amazon ECR...
      - aws --profile source-ecr ecr get-login-password | docker login --username AWS --password-stdin $SOURCE_AWS_ACCOUNT_ID.dkr.ecr.$SOURCE_AWS_REGION.amazonaws.com
      - echo successfully logged in to source ecr
  build:
    commands:
      - echo In build stage
      - docker images
  post_build:
    commands:
      - echo "Post:post_build phase"
